apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-food-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-food-app
  template:
    metadata:
      labels:
        app: fiap-food-app
    spec:
      containers:
        - name: fiap-food-app
          image: guigon/fiap-food-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE_NAME
              value: 'local'
            - name: DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: url
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: DATASOURCE_PWD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password